<?xml version="1.0" encoding="utf-8"?><Database Name="CarBoyDBLive" Class="DataAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.16.32.33;Initial Catalog=CarBoyDBLive;Persist Security Info=True;User ID=sa" SettingsObjectName="MBProtoLib.Properties.Settings" SettingsPropertyName="CarBoyDBLiveConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MBProto_sessionTbl" Member="MBProto_sessionTbls">
    <Type Name="MBProto_sessionTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="sessionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="authKeyID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="diffKey" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="messageIdCollection" Type="System.String" DbType="NVarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="regDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CustomerTbl_MBProto_sessionTbl" Member="CustomerTbl" ThisKey="customerID" OtherKey="ID" Type="CustomerTbl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MBProto_user_sessionTbl" Member="MBProto_user_sessionTbls">
    <Type Name="MBProto_user_sessionTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="sessionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="authKeyID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="diffKey" Type="System.String" DbType="NVarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="messageIdCollection" Type="System.String" DbType="NVarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="regDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserTbl_MBProto_user_sessionTbl" Member="UserTbl" ThisKey="userID" OtherKey="ID" Type="UserTbl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerTbl" Member="CustomerTbls">
    <Type Name="CustomerTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="family" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="lastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="regDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="signCode" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="signCodeRegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="wallet" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="signCodeRerty" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="CustomerTbl_MBProto_sessionTbl" Member="MBProto_sessionTbls" ThisKey="ID" OtherKey="customerID" Type="MBProto_sessionTbl" />
    </Type>
  </Table>
  <Table Name="dbo.UserTbl" Member="UserTbls">
    <Type Name="UserTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="family" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="Char(32) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="lastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="registerDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="isManager" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isOperator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isRepairman" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isDistributor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isWarehouseKeeper" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="signCode" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="signCodeRegDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="repairmanServiceCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="repairmanScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserTbl_MBProto_user_sessionTbl" Member="MBProto_user_sessionTbls" ThisKey="ID" OtherKey="userID" Type="MBProto_user_sessionTbl" />
    </Type>
  </Table>
</Database>